### PR TITLE
new GCABI, dual16 info, .. 

### PR DESCRIPTION
**Pull request by flto**

### CODE REVIEW

**Comment by austriancoder** [comment]
The last patch "rnndb: unify COLOR_COMPRESSION_FORMAT and TS_SAMPLER_FORMAT" breaks gen_headers.sh. You can not simply rename enums without updating the references. Also I think we should call the enum simply COMPRESSION_FORMAT.

What about the following patch?
[https://github.com/austriancoder/etna_viv/commit/85a84d38972a76892817c6e6815011a9c798e677](https://github.com/austriancoder/etna_viv/commit/85a84d38972a76892817c6e6815011a9c798e677)

**Comment by flto** [comment]
Sorry about that, I forgot to run the header generation (was using manually modified headers before I made the rnndb changes) . That patch looks good, but I wonder, if the TS_SAMPLER_CONFIG_FORMAT needs to be set when compression isn't used, then maybe calling it compression format is wrong.

**Comment by flto** [comment]
Replaced the commit with yours and added a new one.

**Comment by flto** [comment]
Calling it COMPRESSION_FORMAT looks good since in my tests the TS_SAMPLER_CONFIG_FORMAT didn't seem to matter without compression.

**Comment by austriancoder** [comment]
Thanks!

**Comment by laanwj** [comment]
Thanks !

**Pull request merged**
